name: 'docker-base'

services:
  ruby:
    container_name: ${APP_NAME}.ruby
    build:
      context: ./ruby
      dockerfile: Dockerfile
      args:
        - PACKAGE_VERSION=3.2.1
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${FORWARD_PHP_HTTP_PORT:-3000}:3000'
      - '${FORWARD_PHP_HTTPS_PORT:-3001}:3001'
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    command:


networks:
  default:
    name: '${APP_NAME}.net'
    driver: bridge

volumes:
  'vol.postgresql':
    name: '${APP_NAME}.vol.postgresql'
    driver: local
