services:
  devcontainer:
    extends:
      file: ../php/docker-compose.yml
      service: devcontainer
    build:
      context: ./devcontainer

  ruby:
    container_name: ${APP_NAME}.ruby
    image: ghcr.io/rails/cli:latest
    ports:
      - '${FORWARD_PHP_HTTP_PORT:-3000}:3000'
    command: "rails server"
    volumes:
      - '$HOME/Development/99linesofcode/${APP_NAME}:/rails'

  mysql:
    extends:
      file: ../php/docker-compose.yml
      service: mysql

  redis:
    extends:
      file: ../php/docker-compose.yml
      service: redis

  phpmyadmin:
    extends:
      file: ../php/docker-compose.yml
      service: phpmyadmin
    depends_on:
      - mysql

networks:
  default:
    name: '${APP_NAME}.net'
    driver: bridge

volumes:
  'vol.mysql':
    name: '${APP_NAME}.vol.mysql'
    driver: local
  'vol.redis':
    name: '${APP_NAME}.vol.redis'
    driver: local
