services:
  devcontainer:
    container_name: ${APP_NAME}.devcontainer
    build:
      context: .
      # See https://docs.docker.com/compose/compose-file/build/#ssh
      ssh:
        - default # lets the builder connect to the default SSH agent
      args:
        - PUID=${PUID:-1000}
        - PGID=${PGID:-1000}
        - TZ=${TIMEZONE-Europe/Amsterdam}
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway" # for accessing the host from inside the container
    volumes:
      - $HOME/.ssh:/config/.ssh:ro # the SSH agent will need access to your configuration
      - $HOME/.npmrc:/config/.npmrc # necessary when installing packages from a private repository
      - $HOME/Development/${APP_NAME}:/app

  # Node.js service
  #
  # FIXME serve different urls for process.browser and SSR to avoid CORS issues when SSR
  # FIXME dont volume mount /node_modules to drastically improve performance
  #
  # nodejs:
  #   container_name: ${APP_NAME}.nodejs
  #   image: node:alpine
  #   user: node
  #   working_dir: /var/www/html
  #   extra_hosts:
  #     - host.docker.internal:host-gateway
  #   ports:
  #     - ${FORWARD_NODE_PORT:-3000}:3000
  #     - ${FORWARD_VITE_PORT:-24678}:24678
  #   environment:
  #     - NODE_ENV=${APP_ENV:-development}
  #     - NUXT_HOST=nodejs
  #     - NUXT_PORT=${FORWARD_NODE_PORT:-3000}
  #   volumes:
  #     - $HOME/Development/${APP_NAME}/nuxt:/var/www/html
  #   command: npm run dev
  #   depends_on: # NOTE: cannot be used when extending, extract to child
  #     - php

  mysql:
    container_name: ${APP_NAME}.mysql
    image: mysql/mysql-server:8.0
    ports:
      - ${FORWARD_DB_PORT:-3306}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s

  redis:
    container_name: ${APP_NAME}.redis
    image: redis:alpine
    ports:
      - ${FORWARD_REDIS_PORT:-6379}:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: ${APP_NAME}.phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - PMA_HOST=${APP_NAME}.mysql
      - PMA_PMADB=phpmyadmin
      - UPLOAD_LIMIT=512M
    restart: unless-stopped
    ports:
      - ${PHPMYADMIN_PORT:-8888}:80
    healthcheck:
      test: ["CMD", "curl", "-Ss", "http://localhost/robots.txt"]
      retries: 3
      timeout: 5s

  mailpit:
    container_name: ${APP_NAME}.mailpit
    image: axllent/mailpit:latest
    ports:
      - ${FORWARD_MAILPIT_PORT:-1025}:1025
      - ${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025
    healthcheck:
      test: ["CMD", "curl", "-Ss", "http://localhost:8025/livez"]
      retries: 3
      timeout: 5s

networks:
  default:
    name: "${APP_NAME}.net"
    driver: bridge
