version: '3'

services:
  base:
    image: linuxserver/nginx
    container_name: development
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=${TIMEZONE}
    volumes:
      - ./config/development/nginx:/config
      - ./src/:/var/www/html
    ports:
      - '${NGINX_HTTP_PORT}:80'
      - '${NGINX_HTTPS_PORT}:443'
    restart: unless-stopped
