version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.override
    environment:
      - SSH_AUTH_SOCK=/config/ssh-agent
    volumes:
      - $SSH_AUTH_SOCK:/config/ssh-agent
      - ../api:/config/www

  adminer:
    image: adminer
    container_name: linesofcode.adminer
    restart: unless-stopped
    ports:
      - 8080:8080
