version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.base
    cap_add:
      - NET_ADMIN
    environment:
      - URL=${DOMAIN}
      - SUBDOMAINS=${SUBDOMAINS},
      - VALIDATION=${VALIDATION}
      - EMAIL=${EMAIL}
