version: "3"

services:
  app:
    container_name: linesofcode.app
    environment:
      - PUID=${PUID:-1000}
      - PGID=${GUID:-1000}
      - TZ=${TIMEZONE:-Europe/Amsterdam}
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - ${NGINX_HTTP_PORT:-80}:80
      - ${NGINX_HTTPS_PORT:-443}:443
    restart: unless-stopped

  mysql:
    image: mysql:8.0.26
    command: --default-authentication-plugin=mysql_native_password
    container_name: linesofcode.mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-laravel}
      - MYSQL_USER=${MYSQL_USER:-default}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-secret}
    ports:
      - ${DB_PORT:-3306}:3306
    restart: unless-stopped
    volumes:
      - ~/.config/${REPOSITORY}/mysql:/var/lib/mysql

  redis:
    image: redis:6-alpine
    container_name: linesofcode.redis
    ports:
      - ${REDIS_PORT:-6379}:6379
    volumes:
      - ~/.config/${REPOSITORY}/redis:/data

networks:
  default:
    name: linesofcode.network
