version: "3"

services:
  base:
    image: linuxserver/letsencrypt
    container_name: production
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=${TIMEZONE}
      - URL=${DOMAIN}
      - SUBDOMAINS=${SUBDOMAINS},
      - VALIDATION=${VALIDATION}
      - EMAIL=${EMAIL}
    volumes:
      - config/production:/config
      - src:/var/www/html
    ports:
      - '${NGINX_HTTP_PORT}:80'
      - '${NGINX_HTTPS_PORT}:443'
    restart: unless-stopped

volumes:
  production:
