version: '3'

services:
  base:
    image: linuxserver/nginx
    container_name: development
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=${TIMEZONE}
      - URL=${DOMAIN}
      - SUBDOMAINS=${SUBDOMAINS},
      - VALIDATION=${VALIDATION}
      - EMAIL=${EMAIL}
    volumes:
      - ./config/nginx:/config
    ports:
      - '${NGINX_HTTP_PORT}:80'
      - '${NGINX_HTTPS_PORT}:443'
    restart: unless-stopped
