services:
  devcontainer:
    extends:
      file: ../php/docker-compose.yml
      service: devcontainer
    build:
      args:
        - PHP_VERSION=8.0
    volumes:
      - $HOME/Development/bttr/${APP_NAME}:/config/www

  php:
    extends:
      file: ../php/docker-compose.yml
      service: php
    build:
      args:
        - PHP_VERSION=8.0
    volumes:
      - $HOME/Development/bttr/${APP_NAME}/api:/config/www
    depends_on:
      - meilisearch
      - mysql
      - redis

  mysql:
    extends:
      file: ../php/docker-compose.yml
      service: mysql

  redis:
    extends:
      file: ../php/docker-compose.yml
      service: redis

  meilisearch:
    extends:
      file: ../php/docker-compose.yml
      service: meilisearch

  phpmyadmin:
    extends:
      file: ../php/docker-compose.yml
      service: phpmyadmin
    depends_on:
      - mysql

  mailpit:
    extends:
      file: ../php/docker-compose.yml
      service: mailpit

volumes:
  vol.mysql:
    name: ${APP_NAME}.vol.mysql
    driver: local
  vol.redis:
    name: ${APP_NAME}.vol.redis
    driver: local
  vol.meilisearch:
    name: ${APP_NAME}.vol.meilisearch
    driver: local
