#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# copy .env if not exists
if [[ ! -f /app/www/.env ]]; then
    install -g abc -o abc /app/www/.env.example /app/www/.env
    echo "Creating app key. This may take a while on slower systems"
    s6-setuidgid abc php /app/www/artisan key:generate
fi

# set queue driver to database by default
sed -i 's/QUEUE_DRIVER=sync/QUEUE_DRIVER=database/' /app/www/.env
