name: 'docker-base'

services:
  postgresql:
    container_name: ${APP_NAME}.postgresql
    image: 'postgres:alpine'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_USER: '${DB_USERNAME:-default}'
      POSTGRES_DB: '${DB_DATABASE:-docker-base}'
    volumes:
      - 'vol.postgres:/var/lib/pgsql'
      # - './vendor/laravel/sail/database/pqsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${DB_USERNAME} -d ${DB_PASSWORD}'"
        ]
      retries: 3
      timeout: 5s

  redis:
    container_name: ${APP_NAME}.redis
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'vol.redis:/data'
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]
      retries: 3
      timeout: 5s

  meilisearch:
    container_name: ${APP_NAME}.meilisearch
    image: 'getmeili/meilisearch:v0.28.1'
    ports:
      - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
    volumes:
      - 'vol.meilisearch:/meili_data'
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--spider',
          'http://localhost:7700/health'
        ]
      retries: 3
      timeout: 5s

  mailhog:
    container_name: ${APP_NAME}.mailhog
    image: 'mailhog/mailhog:latest'
    ports:
      - '${FORWARD_MAILHOG_PORT:-1025}:1025'
      - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'

networks:
  default:
    name: '${APP_NAME}.net'
    driver: bridge

volumes:
  'vol.postges':
    name: '${APP_NAME}.vol.postges'
    driver: local
  'vol.redis':
    name: '${APP_NAME}.vol.redis'
    driver: local
  'vol.meilisearch':
    name: '${APP_NAME}.vol.meilisearch'
    driver: local
