services:
  devcontainer:
    container_name: ${APP_NAME}.devcontainer
    build:
      context: ./devcontainer
      dockerfile: Dockerfile
      # See https://docs.docker.com/compose/compose-file/build/#ssh
      ssh:
        - default
      args:
        - PACKAGE_VERSION=latest
        - PHP_VERSION=8.0
    working_dir: '/config/www'
    # See https://docs.docker.com/compose/environment-variables/envvars-precedence/
    environment:
      - TZ=${TIMEZONE:-Europe/Amsterdam}
    tty: true
    volumes:
      - '/home/${USER}/.npmrc:/config/.npmrc:ro'
      - '/home/${USER}/.config/composer/auth.json:/config/.config/composer/auth.json:ro'
      - '/home/jordy/Development/bttr/${APP_NAME}:/config/www'

  php:
    environment:
      - XDEBUG_MODE=${PHP_XDEBUG_MODE:-off}
      - XDEBUG_CONFIG=${PHP_XDEBUG_CONFIG:-client_host=host.docker.internal}
    volumes:
      - '/home/jordy/Development/bttr/${APP_NAME}/api:/config/www'

  node:
    volumes:
      - '/home/jordy/Development/bttr/${APP_NAME}/nuxt:/config/www'
    command: 'npm run dev'

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: ${APP_NAME}.phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - PMA_HOST=${APP_NAME}.mysql
      - PMA_PMADB=phpmyadmin
      - UPLOAD_LIMIT=512M
    restart: unless-stopped
    ports:
      - ${PHPMYADMIN_PORT:-8888}:80
    depends_on:
      - mysql

  mailpit:
    container_name: ${APP_NAME}.mailpit
    image: 'axllent/mailpit:latest'
    ports:
      - '${FORWARD_MAILHOG_PORT:-1025}:1025'
      - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
