name: 'docker-base'

services:
  php:
    container_name: ${APP_NAME}.php
    build:
      context: ./php/8.1
      dockerfile: Dockerfile
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${FORWARD_PHP_HTTP_PORT:-80}:80'
      - '${FORWARD_PHP_HTTPS_PORT:-443}:443'
    environment:
      - PHP_VERSION=php${PHP_VERSION/./}
      - PUID=${PUID}
      - PGID=${PGID}
    depends_on:
      - meilisearch
      - mysql
      - redis

  mysql:
    container_name: ${APP_NAME}.mysql
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    # volumes:
    #   - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s

  redis:
    container_name: ${APP_NAME}.redis
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'vol.redis:/data'
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]
      retries: 3
      timeout: 5s

  meilisearch:
    container_name: ${APP_NAME}.meilisearch
    image: 'getmeili/meilisearch:v0.28.1'
    ports:
      - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
    volumes:
      - 'vol.meilisearch:/meili_data'
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--spider',
          'http://localhost:7700/health'
        ]
      retries: 3
      timeout: 5s

networks:
  default:
    name: '${APP_NAME}.net'
    driver: bridge

volumes:
  'vol.mysql':
    name: '${APP_NAME}.vol.mysql'
    driver: local
  'vol.redis':
    name: '${APP_NAME}.vol.redis'
    driver: local
  'vol.meilisearch':
    name: '${APP_NAME}.vol.meilisearch'
    driver: local
