services:
  devcontainer:
    container_name: ${APP_NAME}.devcontainer
    build:
      context: ./devcontainer
      dockerfile: Dockerfile
      # See https://docs.docker.com/compose/compose-file/build/#ssh
      ssh:
        - default
    working_dir: '/config/www'
    # See https://docs.docker.com/compose/environment-variables/envvars-precedence/
    environment:
      - PHP_VERSION=8.1
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE:-Europe/Amsterdam}
    tty: true
    volumes:
      - '/home/${USER}/.npmrc:/root/.npmrc'
      - '/home/${USER}/.config/composer/auth.json:/root/.config/composer/auth.json'
      - '/home/jordy/Development/bttr/${APP_NAME}:/config/www'

  php:
    environment:
      - XDEBUG_MODE=${PHP_XDEBUG_MODE:-off}
      - XDEBUG_CONFIG=${PHP_XDEBUG_CONFIG:-client_host=host.docker.internal}
    volumes:
      - '/home/jordy/Development/bttr/${APP_NAME}/api:/config/www'

  node:
    container_name: ${APP_NAME}.node
    image: 'node:18.13.0'
    user: node
    working_dir: '/var/www/html'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${FORWARD_NODE_PORT:-3000}:3000'
      - '${FORWARD_VITE_PORT:-24678}:24678'
    environment:
      - NODE_ENV=${APP_ENV:-development}
      - NUXT_HOST=node
      - NUXT_PORT=${FORWARD_NODE_PORT:-3000}
    volumes:
      - '../nuxt:/var/www/html'
    command: 'npm run dev'
    depends_on:
      - php

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: ${APP_NAME}.phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - PMA_HOST=${APP_NAME}.mysql
      - PMA_PMADB=phpmyadmin
      - UPLOAD_LIMIT=512M
    restart: unless-stopped
    ports:
      - ${PHPMYADMIN_PORT:-8888}:80
    depends_on:
      - mysql

  mailhog:
    container_name: ${APP_NAME}.mailhog
    image: 'mailhog/mailhog:latest'
    ports:
      - '${FORWARD_MAILHOG_PORT:-1025}:1025'
      - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
